import { Transaction } from "./types";

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "TX_001",
    date: "2024-03-01",
    customerId: "CU_01",
    customerName: "Alice Johnson",
    customerEmail: "alice@example.com",
    amount: 150.5,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_002",
    date: "2024-03-01",
    customerId: "CU_02",
    customerName: "Bob Smith",
    customerEmail: "bob@example.com",
    amount: 89.99,
    status: "pending",
    method: "paypal",
  },
  {
    id: "TX_003",
    date: "2024-03-02",
    customerId: "CU_03",
    customerName: "Charlie Davis",
    customerEmail: "charlie@example.com",
    amount: 210.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_004",
    date: "2024-03-02",
    customerId: "CU_04",
    customerName: "Diana Ross",
    customerEmail: "diana@example.com",
    amount: 45.0,
    status: "cancelled",
    method: "stripe",
  },
  {
    id: "TX_005",
    date: "2024-03-03",
    customerId: "CU_05",
    customerName: "Edward Norton",
    customerEmail: "ed@example.com",
    amount: 320.75,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_006",
    date: "2024-03-03",
    customerId: "CU_06",
    customerName: "Fiona Apple",
    customerEmail: "fiona@example.com",
    amount: 12.5,
    status: "refunded",
    method: "paypal",
  },
  {
    id: "TX_007",
    date: "2024-03-04",
    customerId: "CU_07",
    customerName: "George Miller",
    customerEmail: "george@example.com",
    amount: 500.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_008",
    date: "2024-03-04",
    customerId: "CU_08",
    customerName: "Hannah Abbott",
    customerEmail: "hannah@example.com",
    amount: 25.99,
    status: "pending",
    method: "credit_card",
  },
  {
    id: "TX_009",
    date: "2024-03-05",
    customerId: "CU_09",
    customerName: "Ian Wright",
    customerEmail: "ian@example.com",
    amount: 75.0,
    status: "completed",
    method: "stripe",
  },
  {
    id: "TX_010",
    date: "2024-03-05",
    customerId: "CU_10",
    customerName: "Julia Roberts",
    customerEmail: "julia@example.com",
    amount: 120.0,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_011",
    date: "2024-03-06",
    customerId: "CU_11",
    customerName: "Kevin Hart",
    customerEmail: "kevin@example.com",
    amount: 300.25,
    status: "pending",
    method: "bank_transfer",
  },
  {
    id: "TX_012",
    date: "2024-03-06",
    customerId: "CU_12",
    customerName: "Laura Palmer",
    customerEmail: "laura@example.com",
    amount: 55.5,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_013",
    date: "2024-03-07",
    customerId: "CU_13",
    customerName: "Mike Myers",
    customerEmail: "mike@example.com",
    amount: 440.0,
    status: "cancelled",
    method: "stripe",
  },
  {
    id: "TX_014",
    date: "2024-03-07",
    customerId: "CU_14",
    customerName: "Nina Simone",
    customerEmail: "nina@example.com",
    amount: 99.99,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_015",
    date: "2024-03-08",
    customerId: "CU_15",
    customerName: "Oscar Wilde",
    customerEmail: "oscar@example.com",
    amount: 15.0,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_016",
    date: "2024-03-08",
    customerId: "CU_16",
    customerName: "Paul Newman",
    customerEmail: "paul@example.com",
    amount: 250.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_017",
    date: "2024-03-09",
    customerId: "CU_17",
    customerName: "Quentin Tarantino",
    customerEmail: "quentin@example.com",
    amount: 600.75,
    status: "pending",
    method: "stripe",
  },
  {
    id: "TX_018",
    date: "2024-03-09",
    customerId: "CU_18",
    customerName: "Rachel Green",
    customerEmail: "rachel@example.com",
    amount: 110.0,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_019",
    date: "2024-03-10",
    customerId: "CU_19",
    customerName: "Steve Jobs",
    customerEmail: "steve@example.com",
    amount: 1000.0,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_020",
    date: "2024-03-10",
    customerId: "CU_20",
    customerName: "Tina Fey",
    customerEmail: "tina@example.com",
    amount: 45.5,
    status: "refunded",
    method: "bank_transfer",
  },
  {
    id: "TX_021",
    date: "2024-03-11",
    customerId: "CU_21",
    customerName: "Uma Thurman",
    customerEmail: "uma@example.com",
    amount: 125.0,
    status: "completed",
    method: "stripe",
  },
  {
    id: "TX_022",
    date: "2024-03-11",
    customerId: "CU_22",
    customerName: "Victor Hugo",
    customerEmail: "victor@example.com",
    amount: 300.0,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_023",
    date: "2024-03-12",
    customerId: "CU_23",
    customerName: "Will Smith",
    customerEmail: "will@example.com",
    amount: 450.25,
    status: "pending",
    method: "credit_card",
  },
  {
    id: "TX_024",
    date: "2024-03-12",
    customerId: "CU_24",
    customerName: "Xena Warrior",
    customerEmail: "xena@example.com",
    amount: 80.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_025",
    date: "2024-03-13",
    customerId: "CU_25",
    customerName: "Yoko Ono",
    customerEmail: "yoko@example.com",
    amount: 15.75,
    status: "completed",
    method: "stripe",
  },
  {
    id: "TX_026",
    date: "2024-03-13",
    customerId: "CU_26",
    customerName: "Zane Grey",
    customerEmail: "zane@example.com",
    amount: 220.0,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_027",
    date: "2024-03-14",
    customerId: "CU_27",
    customerName: "Arthur Curry",
    customerEmail: "arthur@example.com",
    amount: 50.0,
    status: "cancelled",
    method: "credit_card",
  },
  {
    id: "TX_028",
    date: "2024-03-14",
    customerId: "CU_28",
    customerName: "Bruce Wayne",
    customerEmail: "bruce@example.com",
    amount: 5000.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_029",
    date: "2024-03-15",
    customerId: "CU_29",
    customerName: "Clark Kent",
    customerEmail: "clark@example.com",
    amount: 12.0,
    status: "completed",
    method: "stripe",
  },
  {
    id: "TX_030",
    date: "2024-03-15",
    customerId: "CU_30",
    customerName: "Diana Prince",
    customerEmail: "diana.p@example.com",
    amount: 750.0,
    status: "pending",
    method: "paypal",
  },
  {
    id: "TX_031",
    date: "2024-03-16",
    customerId: "CU_31",
    customerName: "Barry Allen",
    customerEmail: "barry@example.com",
    amount: 35.0,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_032",
    date: "2024-03-16",
    customerId: "CU_32",
    customerName: "Hal Jordan",
    customerEmail: "hal@example.com",
    amount: 90.5,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_033",
    date: "2024-03-17",
    customerId: "CU_33",
    customerName: "Oliver Queen",
    customerEmail: "oliver@example.com",
    amount: 1200.0,
    status: "completed",
    method: "stripe",
  },
  {
    id: "TX_034",
    date: "2024-03-17",
    customerId: "CU_34",
    customerName: "Dinah Lance",
    customerEmail: "dinah@example.com",
    amount: 65.0,
    status: "refunded",
    method: "paypal",
  },
  {
    id: "TX_035",
    date: "2024-03-18",
    customerId: "CU_35",
    customerName: "John Jones",
    customerEmail: "john@example.com",
    amount: 45.25,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_036",
    date: "2024-03-18",
    customerId: "CU_36",
    customerName: "Billy Batson",
    customerEmail: "billy@example.com",
    amount: 10.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_037",
    date: "2024-03-19",
    customerId: "CU_37",
    customerName: "Victor Stone",
    customerEmail: "victor.s@example.com",
    amount: 800.0,
    status: "pending",
    method: "stripe",
  },
  {
    id: "TX_038",
    date: "2024-03-19",
    customerId: "CU_38",
    customerName: "Shayera Hol",
    customerEmail: "shayera@example.com",
    amount: 55.75,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_039",
    date: "2024-03-20",
    customerId: "CU_39",
    customerName: "Katar Hol",
    customerEmail: "katar@example.com",
    amount: 130.0,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_040",
    date: "2024-03-20",
    customerId: "CU_40",
    customerName: "Zatanna Zatara",
    customerEmail: "zatanna@example.com",
    amount: 95.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_041",
    date: "2024-03-21",
    customerId: "CU_41",
    customerName: "John Constantine",
    customerEmail: "john.c@example.com",
    amount: 66.6,
    status: "cancelled",
    method: "stripe",
  },
  {
    id: "TX_042",
    date: "2024-03-21",
    customerId: "CU_42",
    customerName: "Kara Zor-El",
    customerEmail: "kara@example.com",
    amount: 250.0,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_043",
    date: "2024-03-22",
    customerId: "CU_43",
    customerName: "Selina Kyle",
    customerEmail: "selina@example.com",
    amount: 450.0,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_044",
    date: "2024-03-22",
    customerId: "CU_44",
    customerName: "Harley Quinn",
    customerEmail: "harley@example.com",
    amount: 15.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_045",
    date: "2024-03-23",
    customerId: "CU_45",
    customerName: "Pamela Isley",
    customerEmail: "pam@example.com",
    amount: 35.5,
    status: "pending",
    method: "stripe",
  },
  {
    id: "TX_046",
    date: "2024-03-23",
    customerId: "CU_46",
    customerName: "Harvey Dent",
    customerEmail: "harvey@example.com",
    amount: 100.0,
    status: "completed",
    method: "paypal",
  },
  {
    id: "TX_047",
    date: "2024-03-24",
    customerId: "CU_47",
    customerName: "James Gordon",
    customerEmail: "james@example.com",
    amount: 25.0,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_048",
    date: "2024-03-24",
    customerId: "CU_48",
    customerName: "Barbara Gordon",
    customerEmail: "barbara@example.com",
    amount: 88.0,
    status: "completed",
    method: "bank_transfer",
  },
  {
    id: "TX_049",
    date: "2024-03-25",
    customerId: "CU_49",
    customerName: "Dick Grayson",
    customerEmail: "dick@example.com",
    amount: 120.5,
    status: "completed",
    method: "stripe",
  },
  {
    id: "TX_050",
    date: "2024-03-25",
    customerId: "CU_50",
    customerName: "Jason Todd",
    customerEmail: "jason@example.com",
    amount: 45.0,
    status: "refunded",
    method: "paypal",
  },
  {
    id: "TX_051",
    date: "2024-03-26",
    customerId: "CU_51",
    customerName: "Tim Drake",
    customerEmail: "tim@example.com",
    amount: 65.25,
    status: "completed",
    method: "credit_card",
  },
  {
    id: "TX_052",
    date: "2024-03-26",
    customerId: "CU_52",
    customerName: "Damian Wayne",
    customerEmail: "damian@example.com",
    amount: 1500.0,
    status: "pending",
    method: "bank_transfer",
  },
];
